// templates/boxcar-updated/src/pages/About.svelte
<script lang="ts">
  import { brand } from "../data/brand";
  import Icon from "../components/Icon.svelte";
  import PageBanner from "../components/PageBanner.svelte";
  const benefits = [
    [
      "choice",
      "Find your fit",
      "Explore makes and budgets to find your ideal car.",
    ],
    [
      "pricing",
      "See the details",
      "Compare prices, mileage and details before you shortlist.",
    ],
    [
      "finance",
      "Plan your budget",
      "Plan monthly payments with our finance calculator.",
    ],
    [
      "care",
      "Take the next step",
      "Ask about a car and arrange a showroom viewing.",
    ],
  ];
  const questions = [
    [
      "Can I save cars and come back later?",
      "Yes. Use the bookmark on a car to add it to Saved. Your shortlist stays in this browser when browser storage is available.",
    ],
    [
      "How do I compare my shortlist?",
      "Select Compare on a car card. Add up to four cars, then open the comparison to see their specifications together.",
    ],
    [
      "How do I arrange a viewing?",
      "Open Contact and prepare an enquiry with the car's make and model and your preferred visiting time.",
    ],
  ];
</script>

<!-- Boxcar gallery and illustrations with one centered dealer introduction. -->
<section class="bc-inner about-inner-one has-page-banner">
  <PageBanner
    title={`About ${brand.name}`}
    breadcrumb="About us"
    description="Browse our cars and compare your favourites before your next viewing."
  />
  <div class="bc-container">
    <div class="galler-section" aria-label="Showroom photo gallery">
      <div class="exp-block">
        <div class="exp-box">
          <span>{brand.name}</span>
          <h2>
            Your next
            <br />
            chapter.
          </h2>
          <a href="/inventory/" aria-label="Find your next car">
            <Icon name="arrow" size={28} />
          </a>
        </div>
        <figure class="image">
          <img
            src="/media/resource/about-inner1-1.jpg"
            alt="A car key being handed to a customer"
            width="210"
            height="210"
          />
        </figure>
      </div>
      <figure class="image style-center">
        <img
          src="/media/resource/about-inner1-2.jpg"
          alt="A representative holding a tablet in a car showroom"
          width="567"
          height="540"
        />
      </figure>
      <div class="image-block">
        <figure class="image two">
          <img
            src="/media/resource/about-inner1-3.jpg"
            alt="Vehicles on display inside a bright showroom"
            width="567"
            height="300"
          />
        </figure>
        <div class="box-double-img">
          <figure class="image">
            <img
              src="/media/resource/about-inner1-4.jpg"
              alt="Cars displayed inside a showroom"
              width="210"
              height="210"
              loading="lazy"
            />
          </figure>
          <figure class="image">
            <img
              src="/media/resource/about-inner1-5.jpg"
              alt="A handshake beside a car"
              width="327"
              height="210"
              loading="lazy"
            />
          </figure>
        </div>
      </div>
    </div>
    <section class="why-choose-us-section" aria-labelledby="about-benefits">
      <div class="boxcar-title">
        <h2 id="about-benefits">A simpler way to find your next car</h2>
      </div>
      <div class="bc-benefit-grid">
        {#each benefits as [icon, title, text]}
          <div class="choose-us-block">
            <div class="inner-box">
              <div class="icon-box">
                <img
                  src={`/media/resource/boxcar-${icon}.svg`}
                  alt=""
                  width="60"
                  height="60"
                  loading="lazy"
                />
              </div>
              <div class="content-box">
                <h3>{title}</h3>
                <p>{text}</p>
              </div>
            </div>
          </div>
        {/each}
      </div>
    </section>
    <section class="bc-about-cta" aria-labelledby="about-next">
      <h2 id="about-next">Let’s find your next car.</h2>
      <p>Start with the cars. We’ll help you take the next step.</p>
      <div class="bc-actions">
        <a class="bc-button" href="/inventory/">Explore cars</a>
        <a class="bc-button bc-button-outline" href="/contact/">Get in touch</a>
      </div>
    </section>
    <section class="bc-about-faq" aria-labelledby="about-faq">
      <h2 id="about-faq">A few things you might want to know</h2>
      {#each questions as [question, answer]}<details>
          <summary>{question}<Icon name="plus" size={20} /></summary>
          <p>{answer}</p>
        </details>{/each}
    </section>
  </div>
</section>

// templates/modern/apps/web/app/[locale]/about/page.tsx
import { leadSite } from "@repo/marketplace";
import {
  isPublicSitePathEnabled,
  publicSite,
} from "@repo/marketplace/site-config";
import { DealerDesktopHero } from "@repo/marketplace-ui/components/dealer-desktop-hero";
import Image from "@repo/marketplace-ui/components/public-image";
import { getLocalizedPath, normalizeSeoLocale } from "@repo/seo/metadata";
import { ArrowUpRight, Plus } from "lucide-react";
import Link from "next/link";
import { createPublicLocalizedMetadata } from "@/lib/public-metadata";
import { requirePublicSitePath } from "@/lib/public-site-access";
import { getPublicWebBaseUrl } from "@/lib/public-url";
import styles from "../components/boxcar-desktop-pages.module.css";
import { MobileAboutContact } from "../components/mobile-about-contact";
import { PublicMarketplaceFrame } from "../components/public-marketplace-frame";
import { pageCopy } from "../contact/copy";

interface AboutProps {
  params: Promise<{ locale: string }>;
}
export async function generateMetadata({ params }: AboutProps) {
  const { locale } = await params;
  return createPublicLocalizedMetadata({
    baseUrl: getPublicWebBaseUrl(),
    locale,
    path: "/about",
    title: `${locale.startsWith("bg") ? "За нас" : "About us"} | ${leadSite.shortName}`,
    description: locale.startsWith("bg")
      ? "Разгледайте автомобилите и планирайте следващия си оглед."
      : "Browse our cars and plan your next viewing.",
  });
}
export default async function AboutPage({ params }: AboutProps) {
  requirePublicSitePath("/contact");
  const { locale } = await params;
  const normalized = normalizeSeoLocale(locale);
  const bg = normalized === "bg";
  const text = (bulgarian: string, english: string) =>
    bg ? bulgarian : english;
  const path = (href: string) => getLocalizedPath(normalized, href);
  const benefits = [
    {
      icon: "choice",
      title: text("Открийте своя автомобил", "Find your fit"),
      detail: text(
        "Разгледайте марки и бюджети и открийте подходящия автомобил.",
        "Explore makes and budgets to find your ideal car."
      ),
    },
    {
      icon: "pricing",
      title: text("Вижте детайлите", "See the details"),
      detail: text(
        "Сравнете цена, пробег и характеристики преди избора си.",
        "Compare prices, mileage and details before you shortlist."
      ),
    },
    {
      icon: "finance",
      title: text("Планирайте бюджета си", "Plan your budget"),
      detail: text(
        "Разгледайте възможностите за финансиране и месечните вноски.",
        "Explore financing options and monthly payments."
      ),
    },
    {
      icon: "care",
      title: text("Направете следващата стъпка", "Take the next step"),
      detail: text(
        "Попитайте за автомобил и уговорете оглед на място.",
        "Ask about a car and arrange a showroom viewing."
      ),
    },
  ];
  const questions = [
    [
      text(
        "Мога ли да запазя автомобили за по-късно?",
        "Can I save cars and come back later?"
      ),
      text(
        "Използвайте отметката върху автомобил. Изборът се запазва в този браузър, когато е разрешено локално съхранение.",
        "Use the bookmark on a car to add it to Saved. Your shortlist stays in this browser when browser storage is available."
      ),
    ],
    [
      text(
        "Къде мога да разгледам детайлите?",
        "Where can I review the details?"
      ),
      text(
        "Отворете автомобил от наличностите или от запазения избор, за да разгледате снимките, характеристиките и описанието.",
        "Open a car from the inventory or your shortlist to review its photos, specifications and description."
      ),
    ],
    [
      text("Как да уговоря оглед?", "How do I arrange a viewing?"),
      text(
        "Отворете Контакти и се обадете на екипа. Формулярът в този демо шаблон показва само локален преглед и не изпраща съобщения.",
        "Open Contact and call the team. The form in this template demo prepares a local preview without sending a message."
      ),
    ],
  ];
  return (
    <PublicMarketplaceFrame locale={normalized} showMobileDealerHeader={false}>
      <main className={styles.aboutPage}>
        <MobileAboutContact
          locale={normalized}
          services={pageCopy[normalized].services.filter((service) =>
            isPublicSitePathEnabled(service.href, publicSite)
          )}
        />
        <DealerDesktopHero
          description={text(
            "Разгледайте автомобилите и сравнете избора си преди следващия оглед.",
            "Browse our cars and compare your favourites before your next viewing."
          )}
          locale={normalized}
          title={text(
            `За ${leadSite.shortName}`,
            `About ${leadSite.shortName}`
          )}
          variant="page"
        />
        <div className={styles.aboutContent}>
          <section
            aria-label={text(
              "Илюстративна галерия на автосалон",
              "Illustrative showroom gallery"
            )}
            className={styles.gallery}
          >
            <div className={styles.galleryLeft}>
              <div className={styles.chapter}>
                <span>{leadSite.shortName}</span>
                <h2>
                  {text("Следващата ви", "Your next")}
                  <br />
                  {text("глава.", "chapter.")}
                </h2>
                <Link
                  aria-label={text("Открийте автомобил", "Find your next car")}
                  href={path("/cars")}
                >
                  <ArrowUpRight aria-hidden size={28} />
                </Link>
              </div>
              <figure>
                <Image
                  alt={text(
                    "Предаване на ключ за автомобил",
                    "A car key being handed to a customer"
                  )}
                  fill
                  sizes="220px"
                  src="/desktop-boxcars/about-1.jpg"
                />
              </figure>
            </div>
            <figure>
              <Image
                alt={text(
                  "Консултант в автосалон",
                  "A representative in a showroom"
                )}
                fill
                sizes="550px"
                src="/desktop-boxcars/about-2.jpg"
              />
            </figure>
            <div className={styles.galleryRight}>
              <figure>
                <Image
                  alt={text(
                    "Автомобили в светъл автосалон",
                    "Cars in a bright showroom"
                  )}
                  fill
                  sizes="550px"
                  src="/desktop-boxcars/about-3.jpg"
                />
              </figure>
              <div className={styles.galleryPair}>
                {[4, 5].map((number) => (
                  <figure key={number}>
                    <Image
                      alt=""
                      fill
                      sizes="300px"
                      src={`/desktop-boxcars/about-${number}.jpg`}
                    />
                  </figure>
                ))}
              </div>
            </div>
          </section>
          <section className={styles.benefits}>
            <h2>
              {text(
                "По-лесен път към следващия ви автомобил",
                "A simpler way to find your next car"
              )}
            </h2>
            <div className={styles.benefitGrid}>
              {benefits.map((benefit) => (
                <div key={benefit.icon}>
                  <Image
                    alt=""
                    height={60}
                    src={`/desktop-boxcars/about-${benefit.icon}.svg`}
                    width={60}
                  />
                  <h3>{benefit.title}</h3>
                  <p>{benefit.detail}</p>
                </div>
              ))}
            </div>
          </section>
          <section className={styles.aboutAction}>
            <h2>
              {text(
                "Нека открием следващия ви автомобил.",
                "Let’s find your next car."
              )}
            </h2>
            <p>
              {text(
                "Започнете с автомобилите. Ние ще помогнем за следващата стъпка.",
                "Start with the cars. We’ll help you take the next step."
              )}
            </p>
            <div className={styles.aboutActions}>
              <Link className={styles.contactAction} href={path("/cars")}>
                {text("Разгледайте автомобилите", "Explore cars")}
              </Link>
              <Link className={styles.secondaryAction} href={path("/contact")}>
                {text("Свържете се с нас", "Get in touch")}
              </Link>
            </div>
          </section>
          <section className={styles.aboutFaq}>
            <h2>
              {text(
                "Няколко полезни отговора",
                "A few things you might want to know"
              )}
            </h2>
            {questions.map(([question, answer]) => (
              <details key={question}>
                <summary>
                  {question}
                  <Plus aria-hidden size={20} />
                </summary>
                <p>{answer}</p>
              </details>
            ))}
          </section>
        </div>
      </main>
    </PublicMarketplaceFrame>
  );
}
